export const ADD_EQUIPMENT_TO_CART = 'CART/ADD_TO_CART'
export const REMOVE_EQUIPMENT_FROM_CART = 'CART/REMOVE_FROM_CART'
export const INCREASE_EQUIPMENT_AMOUNT = 'CART/INCREASE_EQUIPMENT_AMOUNT'
export const DECREASE_EQUIPMENT_AMOUNT = 'CART/DECREASE_EQUIPMENT_AMOUNT'
