export const FETCH_RENTAL_AND_EQUIPMENTS_FULFILLED = 'RENTAL/FETCH_FULFILLED'

export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL'
export const LOGOUT = 'AUTH/LOGOUT'
export const SET_AUTH_ERROR = 'AUTH/SET_AUTH_ERROR'
export const RESET_AUTH_ERROR = 'AUTH/RESET_AUTH_ERROR'
